### ISSUE TITLE
issue on linux

### ISSUE THREAD

**Issue by jeanpat** [Image-Py/imagepy#10]
Hello and thank you for your app,

Dependencies (requirement.txt) for Imagepy were installed (in a virtual env)  in a linux computer.
ImagePy.bat was renamed into ImagePy.sh

when starting, the program meets an interruption:
```
./ImagePy.sh 
/home/jeanpat/App/imagepy-master/imagepy
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jeanpat/App/imagepy-master/imagepy/__init__.py", line 9, in <module>
    from .imageplus import ImagePlus
  File "/home/jeanpat/App/imagepy-master/imagepy/imageplus.py", line 4, in <module>
    from .core.manager import WindowsManager, ColorManager
  File "/home/jeanpat/App/imagepy-master/imagepy/core/manager/__init__.py", line 10, in <module>
    from .languagemanager import *
  File "/home/jeanpat/App/imagepy-master/imagepy/core/manager/languagemanager.py", line 82, in <module>
    LanguageManager.read()
  File "/home/jeanpat/App/imagepy-master/imagepy/core/manager/languagemanager.py", line 26, in read
    for line in pkl_file.readlines():
  File "/home/jeanpat/Developpements/VirtualEnvs/venv3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 24: invalid start byte
```

**Comment by yxdragon** [comment]
@jeanpat Sorry, I did not test on Linux in this pull. The error is from the languagemanager, I put a chinese dictionary in imagepy/data/language/Chinese.dic, please delete this file. and I will test it on linux later.

And a sh file is nice, I will add it later.

**Comment by yxdragon** [comment]
@jeanpat pull and test again, if OK, let me know please, else if there is error, please delete Chinese.dic.

**Comment by jeanpat** [comment]
The file Chinese.dic is removed and imagepy starts.
Thank you
