### ISSUE TITLE
error when windows anaconda run imagepy

### ISSUE THREAD

**Issue by LiangYongAI** [Image-Py/imagepy#107]
I create an evn named imagepy and pip install all reqired package according to requirement.txt.

(imagepy) F:\github\imagepy>python -m imagepy
Traceback (most recent call last):
  File "d:\Anaconda3\envs\imagepy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\Anaconda3\envs\imagepy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\github\imagepy\imagepy\__main__.py", line 3, in <module>
    from imagepy.core.app import loader, ImagePy
  File "F:\github\imagepy\imagepy\core\app\__init__.py", line 1, in <module>
    from .imagepy import ImagePy
  File "F:\github\imagepy\imagepy\core\app\imagepy.py", line 6, in <module>
    from sciwx.canvas import CanvasNoteBook
  File "F:\github\imagepy\sciwx\canvas\__init__.py", line 2, in <module>
    from .mcanvas import MCanvas, ICanvas, VCanvas
  File "F:\github\imagepy\sciwx\canvas\mcanvas.py", line 4, in <module>
    from .canvas import Canvas
  File "F:\github\imagepy\sciwx\canvas\canvas.py", line 5, in <module>
    from sciapp.object import Image, Shape, mark2shp, Layer, json2shp
  File "F:\github\imagepy\sciapp\object\__init__.py", line 1, in <module>
    from .shape import *
  File "F:\github\imagepy\sciapp\object\shape.py", line 4, in <module>
    import shapely.geometry as geom
  File "d:\Anaconda3\envs\imagepy\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "d:\Anaconda3\envs\imagepy\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "d:\Anaconda3\envs\imagepy\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "d:\Anaconda3\envs\imagepy\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = **CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))**
  File "d:\Anaconda3\envs\imagepy\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by LiangYongAI** [comment]
@yxdragon can you take a look?

**Comment by qyh405** [comment]
it seems the geos package can't be installed. You may try to install this package independently and then return to condo to install imagepy.
My experience is that when I install imagepy with condo, it says that the pystackreg can't be installed and conda stoped to install imagery. I copy the pystackreg from the Pre-compiled package of imagpy (https://github.com/Image-Py/imagepy/releases) into the imagepy install direction. Then reinsitall imagepy again. Now the conda doesn't check pystackreg and successfully install imagery.

**Comment by yxdragon** [comment]
It is the matter of shapely, try the binary whl?

**Comment by HITWenQLi** [comment]
缺少geos_c.dll模块，在https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely，下载对应版本的Shapely的whl文件，重装即可。
Missing geos_ c. dll,  Download the corresponding version of shapely's whl file and reinstall it in https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely.
