### ISSUE TITLE
A problem occurred when laughing in VS code：Any pushed event handlers must have been removed

### ISSUE THREAD

**Issue by selfpowerful** [Image-Py/imagepy#134]
(ImageProcessing) F:\Users>imagepy
ipy
Traceback (most recent call last):
  File "E:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\Python38\env\ImageProcessing\Scripts\imagepy.exe\__main__.py", line 7, in <module>
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\__init__.py", line 31, in
show
    ImagePy(None).Show()
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\mainframe.py", line 52, in __init__
    if IPy.uimode()=='ipy': self.load_aui()
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\mainframe.py", line 96, in load_aui
    self.widgets = widgetsloader.build_widgets(self, 'widgets', 'plugins')
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\widgetsloader.py", line 34, in build_widgets
    return build_widgets_panel(parent, datas, panel)
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\widgetsloader.py", line 21, in build_widgets_panel
    build_widget(choicebook, i)
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\widgetsloader.py", line 10, in build_widget
    parent.AddPage(i(parent), i.title, False )
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\widgets\histogram\histogram_wgt.py", line 17, in __init__
    self.sli_high = FloatSlider(self, (0,255), 0, '')
  File "e:\program files\python38\env\imageprocessing\lib\site-packages\imagepy\ui\widgets\normal.py", line 283, in __init__
    subsizer.Add( self.spin, 0, wx.ALIGN_CENTER|wx.BOTTOM|wx.EXPAND, 5 )
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at ..\..\src\common\sizer.cpp(2114) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored with wxEXPAND
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

**Comment by Cooperoh** [comment]
same

**Comment by leiwang1023** [comment]
+1

**Comment by sheldonxxd** [comment]
same

**Comment by strongsonn** [comment]
+1

**Comment by yxdragon** [comment]
Hi all, Sorry for not reply for a long time. as I can run with vs code successfully:
![image](https://user-images.githubusercontent.com/24822467/98465511-68e53f00-2204-11eb-9b73-9fa817e3117a.png)
about the wx's error:
try the newest github's code and update wxpython!
