### ISSUE TITLE
Error in atexit._run_exitfuncs

### ISSUE THREAD

**Issue by Alduin-Y** [Image-Py/imagepy#152]
Traceback (most recent call last):
  File "E:/Tools/python3.6.3/Lib/site-packages/imagepy/__main__.py", line 4, in <module>
    imagepy.show()
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\__init__.py", line 31, in show
    ImagePy(None).Show()
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\mainframe.py", line 52, in __init__
    if IPy.uimode()=='ipy': self.load_aui()
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\mainframe.py", line 96, in load_aui
    self.widgets = widgetsloader.build_widgets(self, 'widgets', 'plugins')
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\widgetsloader.py", line 34, in build_widgets
    return build_widgets_panel(parent, datas, panel)
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\widgetsloader.py", line 21, in build_widgets_panel
    build_widget(choicebook, i)
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\widgetsloader.py", line 10, in build_widget
    parent.AddPage(i(parent), i.title, False )
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\widgets\histogram\histogram_wgt.py", line 17, in __init__
    self.sli_high = FloatSlider(self, (0,255), 0, '')
  File "E:\Tools\python3.6.3\lib\site-packages\imagepy\ui\widgets\normal.py", line 283, in __init__
    subsizer.Add( self.spin, 0, wx.ALIGN_CENTER|wx.BOTTOM|wx.EXPAND, 5 )
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at ..\..\src\common\sizer.cpp(2114) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored with wxEXPAND
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

How can I solve this problem

**Comment by qixinbo** [comment]
Which version is your wxpython? You may set it to 4.0.7 to have a try.
