### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wuyuzaizai** [Image-Py/imagepy#29]
hi, i need help, when i start imagepy by "python -m imagepy", ubuntu16.04 python2.7

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/imagepy/__init__.py", line 10, in <module>
    from .ui.imagepy import ImagePy
  File "/usr/local/lib/python2.7/dist-packages/imagepy/ui/imagepy.py", line 9, in <module>
    from .. import IPy, root_dir
  File "/usr/local/lib/python2.7/dist-packages/imagepy/IPy.py", line 11, in <module>
    from wx.lib.pubsub import pub
  File "/usr/local/lib/python2.7/dist-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
  File "/usr/local/lib/python2.7/dist-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax

**Comment by jni** [comment]
I'm not sure why I'm tagged here, but that syntax is Python 3-only syntax. You should either upgrade to Python 3, or revert to a "pubsub" version that is not Py3-only. (I don't know anything about wx or pubsub, so I can't be any more help than that.)

**Comment by HelioGuilherme66** [comment]
@wuyuzaizai Downgrade pypubsub to `pip install -U pypubsub==3.3.0`.

**Comment by yxdragon** [comment]
@wuyuzaizai please make sure your wxpython is 4.0+, I think your version is v2.8.
 ImagePy can run under python2.7 and python3.x, but python3 is recommended.

**Comment by wuyuzaizai** [comment]
@yxdragon  i tried python2 and python3, failed again 
zhaojiajia@zjj:~$ python -m imagepy
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/imagepy/__init__.py", line 10, in <module>
    from .ui.imagepy import ImagePy
  File "/usr/local/lib/python2.7/dist-packages/imagepy/ui/imagepy.py", line 9, in <module>
    from .. import IPy, root_dir
  File "/usr/local/lib/python2.7/dist-packages/imagepy/IPy.py", line 11, in <module>
    from wx.lib.pubsub import pub
  File "/usr/local/lib/python2.7/dist-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
  File "/usr/local/lib/python2.7/dist-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax
zhaojiajia@zjj:~$ python3 -m imagepy
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/dist-packages/imagepy/__init__.py", line 10, in <module>
    from .ui.imagepy import ImagePy
  File "/usr/local/lib/python3.5/dist-packages/imagepy/ui/imagepy.py", line 12, in <module>
    from . import pluginloader, toolsloader, widgetsloader
  File "/usr/local/lib/python3.5/dist-packages/imagepy/ui/pluginloader.py", line 3, in <module>
    from ..core.loader import loader
  File "/usr/local/lib/python3.5/dist-packages/imagepy/core/loader/loader.py", line 8, in <module>
    from ..engine import Macros, MkDown, Widget
  File "/usr/local/lib/python3.5/dist-packages/imagepy/core/engine/__init__.py", line 1, in <module>
    from .filter import Filter
  File "/usr/local/lib/python3.5/dist-packages/imagepy/core/engine/filter.py", line 12, in <module>
    from ...ui.panelconfig import ParaDialog
  File "/usr/local/lib/python3.5/dist-packages/imagepy/ui/panelconfig.py", line 5, in <module>
    from .widgets import NumCtrl, ColorCtrl, FloatSlider
  File "/usr/local/lib/python3.5/dist-packages/imagepy/ui/widgets/__init__.py", line 1, in <module>
    from .curvepanel import CurvePanel
  File "/usr/local/lib/python3.5/dist-packages/imagepy/ui/widgets/curvepanel.py", line 4, in <module>
    from scipy import interpolate
  File "/usr/lib/python3/dist-packages/scipy/interpolate/__init__.py", line 158, in <module>
    from .interpolate import *
  File "/usr/lib/python3/dist-packages/scipy/interpolate/interpolate.py", line 27, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "scipy/interpolate/interpnd.pyx", line 1, in init scipy.interpolate.interpnd (scipy/interpolate/interpnd.c:25150)
  File "/usr/lib/python3/dist-packages/scipy/spatial/__init__.py", line 94, in <module>
    from ._plotutils import *
  File "/usr/lib/python3/dist-packages/scipy/spatial/_plotutils.py", line 4, in <module>
    from scipy._lib.decorator import decorator as _decorator
ImportError: No module named 'scipy._lib.decorator'

**Comment by wuyuzaizai** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/__init__.py", line 10, in <module>
    from .ui.mainframe import ImagePy
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/ui/mainframe.py", line 12, in <module>
    from . import pluginloader, toolsloader, widgetsloader
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/ui/pluginloader.py", line 3, in <module>
    from ..core.loader import loader
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/core/loader/loader.py", line 8, in <module>
    from ..engine import Macros, MkDown, Widget
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/core/engine/__init__.py", line 1, in <module>
    from .filter import Filter
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/core/engine/filter.py", line 12, in <module>
    from ...ui.panelconfig import ParaDialog
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/ui/panelconfig.py", line 5, in <module>
    from .widgets import *
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/ui/widgets/__init__.py", line 6, in <module>
    from .cmapselect import CMapSelPanel
  File "/home/zhaojiajia/ZJJCodes/imagepy/imagepy/ui/widgets/cmapselect.py", line 4, in <module>
    import wx.adv
  File "/usr/local/lib/python3.5/dist-packages/wx/adv.py", line 13, in <module>
    from ._adv import *
ImportError: libSDL-1.2.so.0: cannot open shared object file: No such file or directory

**Comment by wuyuzaizai** [comment]
@yxdragon i have a new error ImportError: libSDL-1.2.so.0: cannot open shared object file: No such file or directory

**Comment by wuyuzaizai** [comment]
@yxdragon thx, the problem is sloved. python3 + sudo apt-get install --reinstall libsdl1.2debian
