### ISSUE TITLE
 File "imagepy.py", line 9, in <module> from .. import IPy ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by caimt** [Image-Py/imagepy#32]
Hi, I need help when I start image.py by "python -m imagepy", in ubuntu14.04 python2.7 I have the following problem:

caimt @ caimt-desktop ~ / anaconda / pkgs / imagepy-0.17-py_0 / site-packages / imagepy / ui $ python -m imagepy.py
Traceback (most recent call last):
   File "/home/caimt/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
     mod_name, _Error)
   File "/home/caimt/anaconda/lib/python2.7/runpy.py", line 102, in _get_module_details
     loader = get_loader (mod_name)
   File "/home/caimt/anaconda/lib/python2.7/pkgutil.py", line 462, in get_loader
     return find_loader (fullname)
   File "/home/caimt/anaconda/lib/python2.7/pkgutil.py", line 472, in find_loader
     for importer in iter_importers (fullname):
   File "/home/caimt/anaconda/lib/python2.7/pkgutil.py", line 428, in iter_importers
     __import __ (pkg)
   File "imagepy.py", line 9, in <module>
     from .. import IPy
ValueError: Attempted relative import in non-package

Is there a solution?
Thank you very much.

**Comment by yxdragon** [comment]
did you install by anaconda? please down load the newest code from github, the conda version is little out of date. and it looks like pkgutil change the default work path. I can run on ubuntu 16.4 with python3.

**Comment by yxdragon** [comment]
@caimt did you install by anaconda? please down load the newest code from github, the conda version is little out of date. and it looks like pkgutil change the default work path. I can run on ubuntu 16.4 with python3
