### ISSUE TITLE
Error with save on linux

### ISSUE THREAD

**Issue by Valinnor-W** [Image-Py/imagepy#36]
`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/customer/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/customer/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/customer/Data/imagepy/imagepy/core/engine/simple.py", line 64, in runasyn
    self.run(ips, imgs, para)
  File "/home/customer/Data/imagepy/imagepy/core/util/fileio.py", line 75, in run
    write2 = write or WriterManager.get(fe[1:], 'imgs')
  File "/home/customer/Data/imagepy/imagepy/core/manager/iomanager.py", line 50, in get
    if ext.lower() in cls.writer[tag]:
KeyError: 'imgs'`

That's a big bug,please fix it ...

**Comment by yxdragon** [comment]
hi, can you tell me your operate witch cause this bug?
