### ISSUE TITLE
JPG format file open error, the same problem occurs on different machines

### ISSUE THREAD

**Issue by pengguanjun** [Image-Py/imagepy#39]
show img
170822 >>> deleted ips
Traceback (most recent call last):
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\wx\core.py", line 3240, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pubsub\core\publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pubsub\core\topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pubsub\core\topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "C:\Users\MaiBenBen\Python36\lib\site-packages\pubsub\core\listener.py", line 237, in __call__
    cb(**kwargs)
  File "C:\Users\MaiBenBen\Desktop\imagepy-master(2)\imagepy-master\imagepy\IPy.py", line 71, in showimg
    ips = ImagePlus(imgs, title)
  File "C:\Users\MaiBenBen\Desktop\imagepy-master(2)\imagepy-master\imagepy\core\wraper\imageplus.py", line 32, in __init__
    self.set_imgs(imgs)
  File "C:\Users\MaiBenBen\Desktop\imagepy-master(2)\imagepy-master\imagepy\core\wraper\imageplus.py", line 42, in set_imgs
    self.height, self.width = self.size = self.imgs[0].shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by pengguanjun** [comment]
import matplotlib.pyplot as plt
from skimage.io import imread
img = imread('C:/Users/MaiBenBen/Desktop/块度图像分析/原图/170809/0815.jpg')
plt.imshow( img )
plt.show()
在ImagePy的命令栏这样可以导入我的图片，是否是路径里面有中文字符的原因报错呢？我去试试

**Comment by yxdragon** [comment]
that is because skimage.io.imread, I had used imageio.imread instead.
