### ISSUE TITLE
Error when opening an image

### ISSUE THREAD

**Issue by CsatiZoltan** [Image-Py/imagepy#80]
The lastest version of ImagePy on Linux throws the following error when I open any image:

```
(__main__.py:330): Gdk-CRITICAL **: 11:41:03.714: IA__gdk_drawable_get_depth: assertion 'GDK_IS_DRAWABLE (drawable)' failed

(__main__.py:330): Gtk-CRITICAL **: 11:41:03.714: IA__gtk_paint_layout: assertion 'style->depth == gdk_drawable_get_depth (window)' failed
show img
Traceback (most recent call last):
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/pubsub/core/topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/pubsub/core/topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/pubsub/core/listener.py", line 237, in __call__
    cb(**kwargs)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/imagepy/IPy.py", line 72, in showimg
    showips(ips)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/imagepy/IPy.py", line 47, in showips
    canvasp = CanvasPanel(curapp.canvasnb)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/imagepy/ui/canvasframe.py", line 37, in __init__
    self.canvas.set_handler(self.set_info)
AttributeError: 'Canvas' object has no attribute 'set_handler'
```
I went into debugging mode and `self.canvas` really doesn't have a `set_handler` method.

**Comment by CsatiZoltan** [comment]
I close this issue. The sure solution is to install it to a new environment with _conda_. Then it works.
